name: bclock
description: A minimalist clock app with analog/digital, stopwatch, world clocks, and alarms.
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5+1
  intl: ^0.20.3
  window_manager: ^0.5.2
  shared_preferences: ^2.5.5
  audioplayers: ^6.8.1
  timezone: ^0.11.1
  plinth_components: 1.9.0
  plinth_hooks: 1.9.0
  plinth_blocks: 0.4.0
  flutter_local_notifications: ^22.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/sounds/alarm.wav
    - assets/icons/
