/// What a ringing alarm or timer plays.
enum AlarmSound {
  /// Four quick beeps: the default.
  beeps('sounds/alarm.wav'),
  chime('sounds/chime.wav'),
  pulse('sounds/pulse.wav'),

  /// A file the user chose ([SoundOptions.customPath]).
  custom(null);

  const AlarmSound(this.asset);

  /// The bundled asset, generated by tools/make_assets.py; null for
  /// [custom].
  final String? asset;
}

/// The user's ring settings, owned by AppProvider and read by AlarmService.
class SoundOptions {
  const SoundOptions({
    this.sound = AlarmSound.beeps,
    this.customPath,
    this.volume = 1.0,
    this.fadeIn = false,
  });

  final AlarmSound sound;

  /// The user's own audio file, used when [sound] is [AlarmSound.custom].
  final String? customPath;

  /// 0.0 to 1.0.
  final double volume;

  /// Start quietly and rise to [volume] over [fadeDuration].
  final bool fadeIn;

  static const Duration fadeDuration = Duration(seconds: 30);

  /// Where a fade starts, as a share of [volume]: audible, not silent.
  static const double fadeStart = 0.15;

  SoundOptions copyWith({
    AlarmSound? sound,
    String? customPath,
    double? volume,
    bool? fadeIn,
  }) =>
      SoundOptions(
        sound: sound ?? this.sound,
        customPath: customPath ?? this.customPath,
        volume: volume ?? this.volume,
        fadeIn: fadeIn ?? this.fadeIn,
      );
}
